channels:
    - conda-forge
dependencies:
    - python=2.7
    - numpy
    - networkx
    - matplotlib
    - pandas
    - numba
    - numexpr
    - cython     
    - scipy
    - bokeh
    - rise
    - pip:
        - jupyter-contrib-nbextensions
